server:
  host: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shortener?serverTimezone=UTC&useLegacyDatetimeCode=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver